#index:
#    path: /
#    controller: App\Controller\DefaultController::index
info:
    path: /index
    controller: App\Controller\BaseController::index

add:
    path: /contacts
    controller: App\Controller\BaseController::contacts